begin;

create extension if not exists pgcrypto;

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  inviter_user_id bigint not null
    references public.users(id)
    on update cascade
    on delete cascade,
  inviter_telegram_id bigint not null,
  referral_code text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint referrals_code_format_check
    check (referral_code ~ '^QZ[A-Z0-9]{4,10}$')
);

create unique index if not exists referrals_inviter_user_id_key
  on public.referrals(inviter_user_id);

create unique index if not exists referrals_inviter_telegram_id_key
  on public.referrals(inviter_telegram_id);

create unique index if not exists referrals_referral_code_key
  on public.referrals(referral_code);

create table if not exists public.referral_claims (
  id bigint generated by default as identity primary key,

  referral_id bigint not null
    references public.referrals(id)
    on update cascade
    on delete restrict,

  inviter_user_id bigint not null
    references public.users(id)
    on update cascade
    on delete restrict,

  invited_user_id bigint not null
    references public.users(id)
    on update cascade
    on delete cascade,

  inviter_telegram_id bigint not null,
  invited_telegram_id bigint not null,

  inviter_reward_points bigint not null,
  invited_reward_points bigint not null,

  claimed_at timestamptz not null default now(),

  constraint referral_claims_no_self_check
    check (inviter_user_id <> invited_user_id),

  constraint referral_claims_reward_check
    check (
      inviter_reward_points >= 0
      and invited_reward_points >= 0
    )
);

create unique index if not exists referral_claims_invited_user_id_key
  on public.referral_claims(invited_user_id);

create unique index if not exists referral_claims_invited_telegram_id_key
  on public.referral_claims(invited_telegram_id);

create index if not exists referral_claims_inviter_user_id_idx
  on public.referral_claims(inviter_user_id, claimed_at desc);

alter table public.referrals enable row level security;
alter table public.referral_claims enable row level security;

revoke all on table public.referrals from anon, authenticated;
revoke all on table public.referral_claims from anon, authenticated;

create or replace function public.touch_referrals_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists referrals_touch_updated_at on public.referrals;

create trigger referrals_touch_updated_at
before update on public.referrals
for each row
execute function public.touch_referrals_updated_at();

create or replace function public.generate_referral_code()
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_code text;
begin
  loop
    v_code :=
      'QZ' ||
      upper(
        substring(
          encode(gen_random_bytes(8), 'hex')
          from 1 for 6
        )
      );

    exit when not exists (
      select 1
      from public.referrals
      where referral_code = v_code
    );
  end loop;

  return v_code;
end;
$$;

create or replace function public.ensure_referral_link(
  p_user_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user public.users%rowtype;
  v_referral public.referrals%rowtype;
begin
  select *
  into v_user
  from public.users
  where id = p_user_id;

  if not found then
    raise exception 'USER_NOT_FOUND'
      using errcode = 'P0001';
  end if;

  insert into public.referrals (
    inviter_user_id,
    inviter_telegram_id,
    referral_code,
    active
  )
  values (
    v_user.id,
    v_user.telegram_id,
    public.generate_referral_code(),
    true
  )
  on conflict (inviter_user_id)
  do update set
    active = true,
    inviter_telegram_id = excluded.inviter_telegram_id
  returning *
  into v_referral;

  return jsonb_build_object(
    'id', v_referral.id,
    'referral_code', v_referral.referral_code,
    'active', v_referral.active,
    'created_at', v_referral.created_at
  );
end;
$$;

create or replace function public.claim_referral_reward(
  p_invited_user_id bigint,
  p_referral_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_invited public.users%rowtype;
  v_inviter public.users%rowtype;
  v_referral public.referrals%rowtype;

  v_inviter_reward bigint;
  v_invited_reward bigint;

  v_existing_claim public.referral_claims%rowtype;

  v_inviter_points_after bigint;
  v_invited_points_after bigint;

  v_claim_id bigint;
  v_now timestamptz := now();
begin
  if p_referral_code is null
     or trim(p_referral_code) !~ '^QZ[A-Z0-9]{4,10}$' then
    raise exception 'INVALID_REFERRAL_CODE'
      using errcode = 'P0001';
  end if;

  select *
  into v_invited
  from public.users
  where id = p_invited_user_id
  for update;

  if not found then
    raise exception 'USER_NOT_FOUND'
      using errcode = 'P0001';
  end if;

  select *
  into v_existing_claim
  from public.referral_claims
  where invited_user_id = p_invited_user_id
  limit 1;

  if found then
    if v_existing_claim.referral_id = (
      select id
      from public.referrals
      where referral_code = upper(trim(p_referral_code))
      limit 1
    ) then
      return jsonb_build_object(
        'idempotent', true,
        'claim_id', v_existing_claim.id,
        'inviter_reward_points', v_existing_claim.inviter_reward_points,
        'invited_reward_points', v_existing_claim.invited_reward_points,
        'claimed_at', v_existing_claim.claimed_at
      );
    end if;

    raise exception 'REFERRAL_ALREADY_CLAIMED'
      using errcode = 'P0001';
  end if;

  select *
  into v_referral
  from public.referrals
  where referral_code = upper(trim(p_referral_code))
    and active = true
  for update;

  if not found then
    raise exception 'REFERRAL_CODE_NOT_FOUND'
      using errcode = 'P0001';
  end if;

  if v_referral.inviter_user_id = p_invited_user_id then
    raise exception 'SELF_REFERRAL_NOT_ALLOWED'
      using errcode = 'P0001';
  end if;

  select *
  into v_inviter
  from public.users
  where id = v_referral.inviter_user_id
  for update;

  if not found then
    raise exception 'INVITER_NOT_FOUND'
      using errcode = 'P0001';
  end if;

  select nullif(trim(value), '')::bigint
  into v_inviter_reward
  from public.settings
  where key = 'referral_reward_inviter';

  select nullif(trim(value), '')::bigint
  into v_invited_reward
  from public.settings
  where key = 'referral_reward_invited';

  if v_inviter_reward is null or v_inviter_reward < 0 then
    raise exception 'INVALID_INVITER_REWARD'
      using errcode = 'P0001';
  end if;

  if v_invited_reward is null or v_invited_reward < 0 then
    raise exception 'INVALID_INVITED_REWARD'
      using errcode = 'P0001';
  end if;

  insert into public.referral_claims (
    referral_id,
    inviter_user_id,
    invited_user_id,
    inviter_telegram_id,
    invited_telegram_id,
    inviter_reward_points,
    invited_reward_points,
    claimed_at
  )
  values (
    v_referral.id,
    v_inviter.id,
    v_invited.id,
    v_inviter.telegram_id,
    v_invited.telegram_id,
    v_inviter_reward,
    v_invited_reward,
    v_now
  )
  returning id
  into v_claim_id;

  update public.users
  set points = coalesce(points, 0) + v_inviter_reward
  where id = v_inviter.id
  returning points
  into v_inviter_points_after;

  update public.users
  set points = coalesce(points, 0) + v_invited_reward
  where id = v_invited.id
  returning points
  into v_invited_points_after;

  insert into public.leaderboard (
    telegram_id,
    username,
    total_points,
    rank,
    level,
    vip,
    photo_url,
    updated_at
  )
  select
    telegram_id,
    username,
    coalesce(points, 0),
    0,
    level,
    vip,
    photo_url,
    v_now
  from public.users
  where id in (v_inviter.id, v_invited.id)
  on conflict (telegram_id)
  do update set
    username = excluded.username,
    total_points = excluded.total_points,
    level = excluded.level,
    vip = excluded.vip,
    photo_url = excluded.photo_url,
    updated_at = excluded.updated_at;

  return jsonb_build_object(
    'idempotent', false,
    'claim_id', v_claim_id,
    'referral_code', v_referral.referral_code,
    'inviter_reward_points', v_inviter_reward,
    'invited_reward_points', v_invited_reward,
    'inviter_points_after', v_inviter_points_after,
    'invited_points_after', v_invited_points_after,
    'claimed_at', v_now
  );
end;
$$;

commit;

notify pgrst, 'reload schema';
