begin;

create table if not exists public.admin_users (
  user_id bigint primary key references public.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin','super_admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by bigint references public.users(id) on delete set null
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id bigint not null references public.users(id) on delete restrict,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_admin_created_idx
  on public.admin_audit_log (admin_user_id, created_at desc);

alter table public.admin_users enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on public.admin_users from anon, authenticated;
revoke all on public.admin_audit_log from anon, authenticated;

grant all on public.admin_users to service_role;
grant all on public.admin_audit_log to service_role;

commit;

notify pgrst, 'reload schema';
